about/urls.py
from django.urls import path

from .views import IndexTemplateView

app_name = 'about'

urlpatterns = [
    # about/
    # path('', IndexTemplateView.as_view(), name='about_us'),
]

accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.urls import re_path
from django.contrib.auth.decorators import login_required

from django.views.generic import TemplateView


app_name = 'accounts'

urlpatterns = [
    # account/

    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password-change/', login_required(auth_views.PasswordChangeView.as_view(template_name='accounts/password_change_form.html', success_url=reverse_lazy('accounts:logout'))), name='password_change'),

    # class  PasswordChangeView has an builtin login_required as seen in the class dispatch below
    # All CBV do
    # So there is really no need of adding the decorator again as above but lets leave it for now..
    # @method_decorator(sensitive_post_parameters())
    # @method_decorator(csrf_protect)
    # @method_decorator(login_required)
    # def dispatch(self, *args, **kwargs):
    #     return super().dispatch(*args, **kwargs),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html', email_template_name='accounts/password_reset_email.html', subject_template_name='accounts/password_reset_subject.txt', success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password-reset_<uidb64>_<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html', success_url=reverse_lazy('accounts:password_reset_complete')), name='password-reset-confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    # # FOR THE ADMIN, WE ARE GOING TO REDIRECT UNAUTHORISED ACCESS TO A FAKE ADMIN PAGE
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('2021secret1408/', admin.site.urls),

    path('', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),

    path('', include('index.urls')),
    path('about/', include('about.urls')),
    path('account/', include('accounts.urls')),
    
    path('settings/system/', include('personalsettings.urls')),
    path('user/', include('profiles.urls')),
    path('submissions/', include('submissions.urls')),
    path('', include('stats.urls')),


    path('submissions/comments/', include('comment.urls')),
    # path('api/', include('comment.api.urls')),  # only required for API Framework

]

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# # lines below disable the new django admin navbar that is shipped with django3.*
# admin.autodiscover()
# admin.site.enable_nav_sidebar = False

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from django import forms

from django.conf import settings
User = settings.AUTH_USER_MODEL


class LoginForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False, initial=False)

accounts/views.py
import sys
sys.path.append('..')  # Adding a higher directory to python modules path.
import profiles
from profiles.models import Profile

# NB:: THE lines above are for the BLOODY relative import

from .forms import LoginForm

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.contrib import messages

from django.shortcuts import redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.views import LoginView

from django.conf import settings
from django.views.generic import CreateView

User = settings.AUTH_USER_MODEL


# Code below, we are not using because we are going with builtin login class
# class AccountLoginView(bracesviews.AnonymousRequiredMixin, LoginView):
class AccountLoginView(LoginView):
    template_name = "accounts/signin.html"
    form_class = LoginForm

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        stu_mem = self.request.user.profile.type_user

        if remember_me is True:
            ONE_MONTH = 30*24*60*60
            expiry = getattr(settings, "KEEP_LOGGED_DURATION", ONE_MONTH)
            self.request.session.set_expiry(expiry)

        if stu_mem == 'mp' or stu_mem == 'citizen':
            # Redirecting the basic_user to the dashboard
            return redirect('/profile/dashboard')
        elif stu_mem == 'speaker_office':
            # Redirecting the admin to the complaints list page
            return redirect(reverse('complaints:all_complaints'))
        else:
            return redirect(reverse('complaints:all_complaints'))

        # return super(AccountLoginView, self).form_valid(form)   # unindent 4 spaces

accounts/templates/accounts/login.html
{% extends "base/layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock title %}


{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


{% block stylesheets %}{% endblock stylesheets %}


{% block content %}

    <div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
        <div class="row w-100">
            <div class="col-lg-4 mx-auto">


                <span class="sidebar-text" id="siteName">
                    <h2 id="leadHead" class="navbar-nav align-items-center">
                      {% include 'base/site_name.html' %}
                    </h2>
                </span>

                <div class="auto-form-wrapper">

                    <center>
        
                        {% if msg %}
                            <span class="text-danger">{{ msg | safe }}</span>
                        {% else %}
                            Login below.
                        {% endif %}
                        
                    </center>                

                <br />   
                <form method="POST" action="">
                    {% csrf_token %}
                    {{form|crispy}}

                
                    <div class="form-group">
                    <button type="submit" name="login" class="btn btn-primary submit-btn btn-block">
                    Login</button>
                    </div>


                    <div class="form-group d-flex justify-content-between">
                        <div class="form-check form-check-flat mt-0">
                            <label class="form-check-label">
                            <input type="checkbox" class="form-check-input" checked> Keep me signed in </label>
                        </div>
                        <a href="{% url 'accounts:password_reset' %}">
                            <span id="blueLink1" style="font-size: small;">Forgot Password?</span>
                        </a>
                    </div>

        
                </form>
                </div>
                {%comment%}
                <ul class="auth-footer">
                    <li>
                        <a target="_blank" rel="noopener noreferrer" 
                           href="#">AAAAAAA</a>
                    </li>
                    <li>
                        <a target="_blank" rel="noopener noreferrer" 
                           href="#">BBBBBBB</a>
                    </li>
                    <li>
                        <a target="_blank" rel="noopener noreferrer" 
                        href="#">CCCCCCC</a>
                    </li>
                </ul>
                {%endcomment%}
                <br>
                <p class="footer-text text-center">&copy; <a class="text-white" href="#">Tanya Innovations</a></a>
                </p>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends "base/base.html" %}


{% block title %} Logout {% endblock %}

{% block container %}<br>

<div  class="container">
    <h5>You have been logged out</h5>

    <div class="pt-3">
        <small class="text-muted">
            <a  class="btn btn-outline-primary text-light" href="{% url 'accounts:login' %}">
                Log In Again
            </a>
        </small>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends "base/layouts/base.html" %}

{% block title %} Password | Change {% endblock %}

{% load static %}
{% load crispy_forms_tags %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-content">
            <!-- [ Main Content ] start -->
            <div class="row col-sm-10 col-md-8 col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            
                        {%comment%}
                        {% for message in messages %}
                        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}><a class="close" data-dismiss="alert" href="#">&times;</a>{{ message }}</div>
                        {% endfor %}
                        {%endcomment%}

                        <h5 class="pb-4">Change your password here:</h5>

                        <form method="post">
                            {% csrf_token %}
                            {{ form |crispy }}

                            <button class="btn btn-primary mt-4" type="submit">Save and Logout</button>
                        </form>

                        </div>
                    </div>
            </div>
            <!-- [ Main Content ] end -->
        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

accounts/templates/accounts/password_reset.html
{% extends "base/layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock title %}


{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
        <div class="row w-100">
            <div class="col-lg-4 mx-auto">

                <div class="auto-form-wrapper">

                <form method="post" action="">

                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend>
                            <span class="text text-primary" style="font-size: medium;">Enter Recovery Email below</span>
                        </legend>

                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group mt-4">
                        <button class="btn btn-outline-primary" type="submit">
                            <span style="font-size: medium;">Submit Email</span>
                        </button>
                    </div>


                </form>

                </div>

            </div>
        </div>
    </div>

{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base/layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock title %}


{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
        <div class="row w-100">
            <div class="col-lg-4 mx-auto">

                <div class="auto-form-wrapper">
        <h5 class="mt-4 text-success">Success!</h5>
        <br>
        <div class="table-responsive">
            <div class="alert alert-info">
                Congrats! You can now login with the new password.
            </div>
            <div class="mt-4 text-primary">
                <a href="{% url 'accounts:login' %}">
                    <span class="h6" style="text-decoration: underline;">Proceed to Login</span>
                </a>
            </div>
        </div>
    </div>
</div>
</div>
</div>



<!-- Menu Toggle Script -->

{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base/layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock title %}


{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
    <div class="row w-100">
        <div class="col-lg-4 mx-auto">
            <div class="auto-form-wrapper">
                <h5 class="mt-2 text-primary">Comfirm Password change</h5>
                <br>              
                <div class="table-responsive">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">Save new Password</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "base/layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock title %}


{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
        <div class="row w-100">
            <div class="col-lg-4 mx-auto">

                <div class="auto-form-wrapper">
            <h6 class="text-primary">Confirmation of Password change</h6>
            <br>
            <div class="table-responsive">
                <div class="alert alert-info">
                    We just sent you an email with instructions on how to reset your password!
                    If email exists you'll receive these instructions
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}

{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}

{% block reset_link %}

{{ protocol }}://{{ domain }}{% url 'accounts:password-reset-confirm' uidb64=uid token=token %}

{% endblock %}

{% trans "Your login username in case you've forgotten, is:" %} '{{ user.get_username }}'

{% trans "Thanks for using our site!" %}

{% blocktrans %}Regards: The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}