about/urls.py
from django.urls import path

from .views import IndexTemplateView

app_name = 'about'

urlpatterns = [
    # about/
    # path('', IndexTemplateView.as_view(), name='about_us'),
]

index/urls.py
from django.urls import path, include

from .views import IndexTemplateView, UserGuideView

app_name = "index"

urlpatterns = [
    # 127.0.0.1/...
    # path('', IndexTemplateView.as_view(), name="site_index"),

    # the user guide instructions
    path('help/', UserGuideView.as_view(), name="user_guide"),
]


"""
NB.  the index site was coliding with the login side because we are sendind 2 pages to 1 url
So, this index is active as in the template but not the url

Also, the 2 urls can stay active or have the index one off.
the login one cannot go off as it would disappear the login form

then in case of anything to be added to the index page, the index html file is working
as is the login file

"""



#  The error pageurls
handler400 = 'index.views.bad_request_400_view'
handler403 = 'index.views.permission_denied_403_view'
handler404 = 'index.views.page_not_found_404_view'
handler500 = 'index.views.error_500_view'

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    # # FOR THE ADMIN, WE ARE GOING TO REDIRECT UNAUTHORISED ACCESS TO A FAKE ADMIN PAGE
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('2021secret1408/', admin.site.urls),

    path('', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),

    path('', include('index.urls')),
    path('about/', include('about.urls')),
    path('account/', include('accounts.urls')),
    
    path('settings/system/', include('personalsettings.urls')),
    path('user/', include('profiles.urls')),
    path('submissions/', include('submissions.urls')),
    path('', include('stats.urls')),


    path('submissions/comments/', include('comment.urls')),
    # path('api/', include('comment.api.urls')),  # only required for API Framework

]

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# # lines below disable the new django admin navbar that is shipped with django3.*
# admin.autodiscover()
# admin.site.enable_nav_sidebar = False

profiles/urls.py
from django.urls import path

from .views import ( 
	ProfileDetailView, 
	EditProfile, 
	all_profiles_list
	)

app_name = 'profiles'

urlpatterns = [
    # /user/...
    path('list/', all_profiles_list, name='profiles_list'),

    path('<slug>/', ProfileDetailView.as_view(), name='show_self_details'),

    path('<slug>/edit/', EditProfile.as_view(), name='edit_self'),
]

stats/urls.py
from django.urls import path, re_path

from .reports import create_pdf_report_main_table
from .views import (
    GeneralSubmissionCountForTableView,

    # dashboard
    render_all_data_to_dash,

    # statistics page
    render_all_data_for_mp_charts_view, 
   
    # create_pdf_report_main_table,
    # SubmisionsDetailPdfView,
    SubmisionsDetailPdfView2,
    SubmissionDownloadView, 
    # create_pdf_submission_details2
    )


app_name = "stats"

urlpatterns = [
    # /...

    # dashboard
    path('dashboard/', render_all_data_to_dash, name='dashboard'),

    # statistics
    path('stats/cat-nums/', GeneralSubmissionCountForTableView.as_view(), name="submissions_cat_n_region_count"),

    # charts view
    path('charts-view/', render_all_data_for_mp_charts_view, name="charts_view"),
]


""" REPORTS """
urlpatterns += [
    # path('submissions/report', include('model_report.urls')),
    path('submissions/create-pdf-main-table/', create_pdf_report_main_table, name='create_pdf_report_main_table'),
    
    # re_path('^submissions/submission-(?P<pk>[0-9]+)/details/pdf/$', SubmisionsDetailPdfView.as_view(),
    # name='create_pdf_submission_details'),

    # re_path('^submissions/submission-(?P<pk>[0-9]+)/details/pdf/$', SubmisionsDetailPdfView2.as_view(),
    # name='create_pdf_submission_details'),

    re_path('^submissions/submission-(?P<pk>[0-9]+)/details/pdf/$', SubmissionDownloadView.as_view(), name='create_pdf_submission_details'),
    # # re_path('^submissions/submission-(?P<pk>[0-9]+)/details/pdf/$', create_pdf_submission_details2, name='create_pdf_submission_details'),

]

submissions/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.decorators import login_required

# from .filters import *
from .views import (SubmissionCreateView,

                    AllSubmissionsListView,
                    SolvedSubmissionsListView,
                    UnsolvedSubmissionsListView,

                    the_speaker_all_submissions_list,
                    # TheSpeakerAllSubmissionsListView,

                    # TheSpeakerUnsolvedSubmissionsListView,
                    the_speaker_unsolved_submissions_list,

                    # TheSpeakerSolvedSubmissionsListView,
                    the_speaker_solved_submissions_list,

                    SubmissionUpdateView,
                    SubmissionStatusSpeakerUpdateView,
                    # SubmissionsDatatableView,
                    SubmissionsDetailView,
                    )

app_name = 'submissions'

urlpatterns = [
    # submissions/

    # create new submission
    path('create/', SubmissionCreateView.as_view(), name='submission_create'),

    # mp
    path('all/me/', AllSubmissionsListView.as_view(), name='all_submissions'),
    path('unresolved/me/', UnsolvedSubmissionsListView.as_view(), name='unsolved_submissions'),
    path('solved/me/', SolvedSubmissionsListView.as_view(), name='solved_submissions'),

    # speaker
    path('all/global/', the_speaker_all_submissions_list, name='thespeaker_all_submissions'),
    # path('all/global/', TheSpeakerAllSubmissionsListView.as_view(), name='thespeaker_all_submissions'),

    # path('unresolved/global/', TheSpeakerUnsolvedSubmissionsListView.as_view(), name='thespeaker_unsolved_submissions'),
    path('unsolved/global/', the_speaker_unsolved_submissions_list, name='thespeaker_unsolved_submissions'),

    # path('solved/global/', TheSpeakerSolvedSubmissionsListView.as_view(), name='thespeaker_solved_submissions'),
    path('solved/global/', the_speaker_solved_submissions_list, name='thespeaker_solved_submissions'),

    # more..
    re_path('^submission-(?P<pk>[0-9]+)/details/$', SubmissionsDetailView.as_view(), name='submission_detail'),

    re_path('^submission-(?P<pk>[0-9]+)/details/update/$', SubmissionUpdateView.as_view(), name='submission_update'),
    
    # CHANGING THE SUBMISSION STATUS
    re_path('^submission-(?P<pk>[0-9]+)/details/update/status/$', SubmissionStatusSpeakerUpdateView.as_view(), name='submission_status_update'),
 


    # path('submissions-list', SubmissionsNonTableListView.as_view(), name='submissions_list_non_table'),   
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

# Create your views here.

base/templates/base/includes/auth_footer.html
    <!-- partial:partials/_footer.html -->
    <footer class="footer">
      <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">
            &copy; <a target="_blank" 
                      rel="sponsored noopener noreferrer" 
                      href="https://bit.ly/2UTgih5" >BootstrapDash</a>
            - Coded by <a target="_blank" rel="noopener noreferrer"
                          href="https://appseed.us/">AppSeed</a>.          
        </span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">
          <a target="_blank" rel="noopener noreferrer" 
             href="https://appseed.us/admin-dashboards/django-star-admin">Django Star Admin</a>
        </span>
      </div>
    </footer>
    <!-- partial -->

base/templates/base/includes/auth_scripts.html
{% load static %}


<script src="{% static 'static/auth/vendors/js/vendor.bundle.base.js' %}"></script>
<script src="{% static 'static/auth/vendors/js/vendor.bundle.addons.js' %}"></script>
<script src="{% static 'static/auth/js/shared/off-canvas.js' %}"></script>
<script src="{% static 'static/auth/js/shared/misc.js' %}"></script>



<!-- LOBSTER FONT -->
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

base/templates/base/includes/footer.html
<!-- The footer including on all pages -->

<footer class="footer section fixed-bottom" style="background-color: whitesmoke;">
    <div class="col-12 col-lg-6">
        <!-- List -->
        <ul class="list-inline list-group-flush list-group-borderless text-center text-xl-right mb-0">
            <li class="list-inline-item px-0 px-sm-2">
                <a class="text text-muted">&copy; {% now 'Y' %} {% include 'base/site_name.html' %}</a>
            </li>
        </ul>
    </div>
</footer>

base/templates/base/includes/live_scripts.html
{% load static %}



<script src="{% static 'static/assets/js/vendor-all.min.js' %}"></script>
<script src="{% static 'static/assets/js/plugins/bootstrap.min.js' %}"></script>
<script src="{% static 'static/assets/js/pcoded.min.js' %}"></script>


<!-- LOBSTER FONT -->
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">






<!-- LIVE CDNS  -->
{%comment%}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>


{%endcomment%}















<!-- highcharts lib -->
<!-- <script src="https://code.highcharts.com/highcharts.src.js"></script> -->


<!-- j query -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

<!-- datatables js -->
<script src="//cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>

<!-- datatables css -->
<link href="//cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />

<!-- LOBSTER FONT -->
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">



<!-- LOBSTER FONT -->
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">



<!-- Chartjs libraries -->
<script src="http://code.highcharts.com/stock/highstock.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<script src="http://code.highcharts.com/modules/offline-exporting.js"></script>
<script src="http://code.highcharts.com/modules/export-data.js"></script>
<script src="http://code.highcharts.com/modules/series-label.js"></script>
<script src="http://code.highcharts.com/modules/data.js"></script>

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>


<!-- bootgrid -->




<!-- datatables -->

base/templates/base/includes/navigation.html
{% load static %}
    

<!-- [ Header ] start -->
<header class="navbar pcoded-header navbar-expand-lg navbar-light headerpos-fixed header-info">
        
    <div class="m-header" id="topNavBar1">
        <a class="mobile-menu" id="mobile-collapse" href="#"><span></span></a>
        <a href="." class="b-brand">
            <!-- ========   change your logo hear   ============ -->
           <span class="sidebar-text" id="siteName">
              <h4 id="leadHead" class="navbar-nav align-items-center">
                  {% include 'base/parliament_num.html' %} Parliament
              </h4>
              {# {% include 'base/site_name.html' %}  #} <i class="flag flag-ug"></i>
        </span>
        </a>
        <a href="#!" class="mob-toggler">
            <i class="feather icon-more-vertical"></i>
        </a>
    </div>
    <div class="collapse navbar-collapse" id="topNavBar2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a href="#!" class="full-screen" onclick="javascript:toggleFullScreen()"><i class="fas fa-expand"></i></a>
            </li>
        </ul>

        <marquee scrollamount="4" class="float-center" behavior="scroll" direction="left"><h7>Representing the people of <span id="#marqueeNav">{{ request.user.profile.district }}, {{ request.user.profile.my_constituency }}</span> constituency</h7></marquee>

        <ul class="navbar-nav ml-auto">
            {%comment%}
            <li>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown"><i class="icon feather icon-bell"></i><span class="badge bg-danger"><span class="sr-only"></span></span></a>
                    <div class="dropdown-menu dropdown-menu-right notification">
                        <div class="noti-head">
                            <h6 class="d-inline-block m-b-0">Notifications</h6>
                            <div class="float-right">
                                <a href="#!" class="m-r-10">mark as read</a>
                                <a href="#!">clear all</a>
                            </div>
                        </div>
                        <ul class="noti-body">
                            <li class="n-title">
                                <p class="m-b-0">NEW</p>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ request.user.profile.image_url|default_if_none:'#' }}" alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>John Doe</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>5 min</span></p>
                                        <p>New ticket Added</p>
                                    </div>
                                </div>
                            </li>
                            <li class="n-title">
                                <p class="m-b-0">EARLIER</p>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="/static/static/assets/images/user/avatar-2.jpg" alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>Joseph William</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>10 min</span></p>
                                        <p>Prchace New Theme and make payment</p>
                                    </div>
                                </div>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="/static/static/assets/images/user/avatar-1.jpg" alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>Sara Soudein</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>12 min</span></p>
                                        <p>currently login</p>
                                    </div>
                                </div>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="/static/static/assets/images/user/avatar-2.jpg" alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>Joseph William</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>Prchace New Theme and make payment</p>
                                    </div>
                                </div>
                            </li>
                        </ul>
                        <div class="noti-footer">
                            <a href="#!">show all</a>
                        </div>
                    </div>
                </div>
            </li>
            {%endcomment%}

            <li>
                <div class="dropdown drp-user">
                    <a href="#!" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ request.user.profile.image_url|default_if_none:'#' }}" class="img-radius wid-40" alt="User-Profile-Image">
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-notification">
                        <div class="pro-head">
                            <img src="{{ request.user.profile.image_url|default_if_none:'#' }}" class="img-radius" alt="User-Profile-Image">
                            <span>
                                {{user.username}}
                            </span>
                        </div>
                        <ul class="pro-body">
                            {% if request.user.is_superuser %}
                                <li class="nav-item"><a href="/2021secret1408/" class="nav-link ">
                                    <span class="pcoded-micon"><i class="feather icon-user"></i></span>
                                    <span class="pcoded-mtext">ADMIN SITE</span></a>
                                </li>
                            {% endif %}
                            <li>
                                <a href="{{ request.user.profile.get_absolute_url }}" class="dropdown-item">
                                    <i class="feather icon-user"></i> My Profile
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:logout' %}" class="dropdown-item">
                                    <i class="feather icon-log-out"></i> Logout
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    

</header>
<!-- [ Header ] end -->

base/templates/base/includes/old_scripts.html
{% load static %}



<script src="{% static 'static/assets/js/vendor-all.min.js' %}"></script>
<script src="{% static 'static/assets/js/plugins/bootstrap.min.js' %}"></script>
<script src="{% static 'static/assets/js/pcoded.min.js' %}"></script>

base/templates/base/includes/sidebar.html
{% load static %}


	<!-- [ navigation menu ] start -->
	<nav class="pcoded-navbar menupos-fixed menu-light ">
		<div class="navbar-wrapper">
			<div class="navbar-content scroll-div " >
				<ul class="nav pcoded-inner-navbar ">

					<li class="nav-item ">
					    <a href="{% url 'stats:dashboard' %}" class="nav-link ">
                            <span class="pcoded-micon">
                                <i class="feather icon-home"></i>
                            </span>
                            <span class="pcoded-mtext">Dashboard</span>
                        </a>
					</li>

					{% if request.user.profile.is_thespeaker %}
						<li class="nav-item"><a href="{% url 'submissions:thespeaker_all_submissions' %}" class="nav-link ">
							<span class="pcoded-micon"><i class="feather icon-list"></i></span>
							<span class="pcoded-mtext">All Submissions</span></a>
						</li>
					{%else%}
						<li class="nav-item"><a href="{% url 'submissions:all_submissions' %}" class="nav-link ">
							<span class="pcoded-micon"><i class="feather icon-list"></i></span>
							<span class="pcoded-mtext">All Submissions</span></a>
						</li>
					{%endif%}


					{% if request.user.profile.is_thespeaker %}
						<li class="nav-item"><a href="{% url 'submissions:thespeaker_unsolved_submissions' %}" class="nav-link ">
							<span class="pcoded-micon"><i class="feather icon-alert-circle"></i></span>
							<span class="pcoded-mtext">Unresolved</span></a>
						</li>
					{%else%}
						<li class="nav-item"><a href="{% url 'submissions:unsolved_submissions' %}" class="nav-link ">
							<span class="pcoded-micon"><i class="feather icon-sidebar"></i></span>
							<span class="pcoded-mtext">Unresolved</span></a>
						</li>
					{%endif%}
					


					{% if request.user.profile.is_thespeaker %}
						<li class="nav-item"><a href="{% url 'submissions:thespeaker_solved_submissions' %}" class="nav-link ">
							<span class="pcoded-micon"><i class="feather icon-check-square"></i></span>
							<span class="pcoded-mtext">Resolved</span></a>
						</li>
					{%else%}
						<li class="nav-item"><a href="{% url 'submissions:solved_submissions' %}" class="nav-link ">
							<span class="pcoded-micon"><i class="feather icon-check-square"></i></span>
							<span class="pcoded-mtext">Resolved</span></a>
						</li>
					{%endif%}
					



          			{% if not request.user.profile.is_thespeaker %}
					<li class="nav-item"><a href="{% url 'submissions:submission_create' %}" class="nav-link ">
						<span class="pcoded-micon"><i class="feather icon-plus-circle"></i></span>
						<span class="pcoded-mtext">Add New</span></a>
					</li>
					{%endif%}
					


					<li class="nav-item pcoded-hasmenu">
						<a href="#!" class="nav-link ">
							<span class="pcoded-micon"><i class="fas fa-table"></i></span>
							<span class="pcoded-mtext">Statistics</span>
						</a>
						<ul class="pcoded-submenu">
							<li><a href="{% url 'stats:submissions_cat_n_region_count' %}">Tables</a></li>

							<li><a href="{% url 'stats:charts_view' %}">Charts & Graphs</a></li>
						</ul>
					</li>

					<li class="nav-item pcoded-menu-caption">
					    <label>Accounts &amp; Profiles</label>
					</li>


					<!-- SPEAKER sees the list of all the mps -->
					{% if request.user.profile.is_thespeaker %}
					<li class="nav-item"><a href="{% url 'profiles:profiles_list' %}" class="nav-link ">
						<span class="pcoded-micon"><i class="feather icon-users"></i></span>
						<span class="pcoded-mtext">All MPs</span></a>
					</li>
					{%endif%}


					{% if request.user.is_superuser %}
					<li class="nav-item"><a href="{% url 'profiles:profiles_list' %}" class="nav-link ">
						<span class="pcoded-micon"><i class="feather icon-users"></i></span>
						<span class="pcoded-mtext">All MPs</span></a>
					</li>
					{% endif %}



					<li class="nav-item"><a href="{{ request.user.profile.get_absolute_url }}" class="nav-link ">
						<span class="pcoded-micon"><i class="feather icon-user"></i></span>
						<span class="pcoded-mtext">My Profile</span></a>
					</li>

					{%comment%}
					{%endcomment%}
					<li class="nav-item"><a href="{% url 'personalsettings:personalsettings' %}" class="nav-link ">
						<span class="pcoded-micon"><i class="feather icon-settings"></i></span>
						<span class="pcoded-mtext">Settings</span></a>
					</li>


					<li class="nav-item"><a href="{% url 'index:user_guide' %}" class="nav-link ">
						<span class="pcoded-micon"><i class="feather icon-help-circle"></i></span>
						<span class="pcoded-mtext">User Guide</span></a>
					</li>


					<li class="nav-item">
					    <a href="{% url 'accounts:logout' %}" 
						   class="nav-link ">
						   <span class="pcoded-micon"><i class="feather icon-log-out"></i></span>
						   <span class="pcoded-mtext">Logout <span class="text-success">@{{ request.user.username }}</span></span>
						</a>
					</li>


				</ul>

				
			</div>
		</div>
	</nav>
    <!-- [ navigation menu ] end -->